#!/usr/bin/env bash

curl -O https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.0.4.tgz
tar -zxvf mongodb-linux-x86_64-3.0.4.tgz
mv mongodb-linux-x86_64-3.0.4 mongodb
rm mongodb-linux-x86_64-3.0.4.tgz

#mkdir -p db